# Generated by Django 5.0 on 2024-01-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0014_admininfo_afa_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
